esphome:
  name: comfoair
  friendly_name: Comfoair

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
# logger:
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  networks: !secret networks
  # use_address: esphome-comfoair.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

external_components:
  - source:
      type: git
      url: https://github.com/bfabio/esphome-comfoair
    components: [comfoair]
    refresh: 0s

uart:
  id: uart_bus
  rx_pin: 44
  tx_pin: 43
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

comfoair:
  name: "ComfoAir 160"
  uart_id: uart_bus
  # type:
  #   name: "type"
  # size:
  #   name: "size"
  intake_fan_speed:
    name: "intake_fan_speed"
  exhaust_fan_speed:
    name: "exhaust_fan_speed"
  intake_fan_speed_rpm:
    name: "intake_fan_speed_rpm"
  exhaust_fan_speed_rpm:
    name: "exhaust_fan_speed_rpm"
  ventilation_level:
    name: "ventilation_level"
  
  bypass_valve_open:
    name: "bypass_valve_open"
  bypass_open_hours:
    name: "bypass_open_hours"

  # Informazioni duplicate / permanenti
  # 
  # bypass_present:
  #   name: "bypass_present"
  # bypass_valve:
  #  name: "bypass_valve"
  # motor_current_bypass:
  #   name: "motor_current_bypass"
  # bypass_factor:
  #   name: "bypass_factor"
  # bypass_step:
  #   name: "bypass_step"
  # bypass_correction:
  #   name: "bypass_correction"

  #
  # Non abbiamo il modulo di pre-riscaldo (preserva lo scambiatore di calore dal congelamento)
  #
  # preheating_state:
  #   name: "preheating_state"
  # preheating_present:
  #   name: "preheating_present"
  # preheating_hours:
  #   name: "preheating_hours"
  # preheating_valve:
  #   name: "preheating_valve"
  # motor_current_preheating:
  #   name: "motor_current_preheating"
  outside_air_temperature:
    name: "outside_air_temperature"
  supply_air_temperature:
    name: "supply_air_temperature"
  return_air_temperature:
    name: "return_air_temperature"
  exhaust_air_temperature:
    name: "exhaust_air_temperature"
  #
  # Non abbiamo lo scambiatore di calore entalpico (https://www.youtube.com/watch?v=b_1lLv5BOwI)
  #
  # enthalpy_present:
  #   name: "enthalpy_present"
  # enthalpy_temperature:
  #   name: "enthalpy_temperature"
  
  #
  # Non abbiamo una pompa di calore terra-acqua
  #
  # Entering Water Temperature: the temperature of the water entering the heat
  # pump from the ground loop heat exchanger.
  # 
  # ewt_temperature:
  #   name: "ewt_temperature"
  # ewt_present:
  #   name: "ewt_present"
  # reheating_temperature:
  #   name: "reheating_temperature"
  #
  # Non abbiamo un sensore delle cappa
  # 
  # kitchen_hood_temperature:
  #   name: "kitchen_hood_temperature"
  #  extractor_hood_switch_off_delay_minutes:
  #  name: "extractor_hood_switch_off_delay_minutes"

  return_air_level:
    name: "return_air_level"
  supply_air_level:
    name: "supply_air_level"
  supply_fan_active:
    name: "supply_fan_active"
  filter_status:
    name: "filter_status"
  
  # options_present:
  #   name: "options_present"  
  # fireplace_present:
  #   name: "fireplace_present"
  # kitchen_hood_present:
  #   name: "kitchen_hood_present"
  # postheating_present:
  #   name: "postheating_present"
  # postheating_pwm_mode_present:
  #   name: "postheating_pwm_mode_present"

  level0_hours:
    name: "level0_hours"
  level1_hours:
    name: "level1_hours"
  level2_hours:
    name: "level2_hours"
  level3_hours:
    name: "level3_hours"
  frost_protection_active:
    name: "frost_protection_active"
  frost_protection_hours:
    name: "frost_protection_hours"
  frost_protection_minutes:
    name: "frost_protection_minutes"
  frost_protection_level:
    name: "frost_protection_level"
  filter_hours:
    name: "filter_hours"

  summer_mode:
    name: "summer_mode"
  # p10_active:
  #   name: "p10_active"
  # p11_active:
  #   name: "p11_active"
  # p12_active:
  #   name: "p12_active"
  # p13_active:
  #   name: "p13_active"
  # p14_active:
  #   name: "p14_active"
  # p15_active:
  #   name: "p15_active"
  # p16_active:
  #   name: "p16_active"
  # p17_active: # summer mode
  #   name: "p17_active"
  # p18_active:
  #   name: "p18_active"
  # p19_active:
  #   name: "p19_active"
  # p90_active:
  #   name: "p90_active"
  # p91_active:
  #   name: "p91_active"
  # p92_active:
  #   name: "p92_active"
  # p93_active:
  #   name: "p93_active"
  # p94_active:
  #   name: "p94_active"
  # p95_active:
  #   name: "p95_active"
  # p96_active:
  #   name: "p96_active"
  # p97_active:
  #   name: "p97_active"

  # Non abbiamo interruttore bagno 
  #
  # bathroom_switch_on_delay_minutes:
  #  name: "bathroom_switch_on_delay_minutes"
  # bathroom_switch_off_delay_minutes:
  #  name: "bathroom_switch_off_delay_minutes"
  
  l1_switch_off_delay_minutes:
    name: "l1_switch_off_delay_minutes"
  boost_ventilation_minutes:
    name: "boost_ventilation_minutes"
  filter_warning_weeks:
    name: "filter_warning_weeks"
  # rf_high_time_short_minutes:
  #   name: "rf_high_time_short_minutes"
  # rf_high_time_long_minutes:
  #   name: "rf_high_time_long_minutes"
  
  # bypass_valve_switch:
  #  name: "bypass_valve_switch"

captive_portal:
    
