substitutions:
  name: esphome-web-fc14e0
  friendly_name: Sensors 2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

i2c:
   - id: bus_a
     sda: GPIO08
     scl: GPIO09
     scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temperature"
      id: bme280_temperature
    pressure:
      name: "Pressure"
      id: bme280_pressure
    humidity:
      name: "Humidity"
      id: bme280_humidity
    i2c_id: bus_a
    address: 0x76
    update_interval: 30s

  #- platform: absolute_humidity
  #  name: "Absolute Humidity"
  #  temperature: bme280_temperature
  #  humidity: bme280_humidity
  #- platform: template
  #  name: "Dew Point"
  #  lambda: |-
  #    return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
  #    (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
  #    ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
  #  unit_of_measurement: °C
  #  icon: 'mdi:thermometer-alert'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}
  networks: !secret networks

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32c3.yaml@v2
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:
